name: Acquire unity activation file

on:
  push:
    branches: [ main ]
    
    # Unity 버전 변경 시 아래 Job을 실행하도록 함
    # 최초 실행 시에는 아래 조건을 제거해야 Action이 실행됩니다 
    # paths: 
    #   - "ProjectSettings/ProjectVersion.txt"

env:
  # 사용하고 있는 Unity version 
  unityVersion: 2021.3.42f1

jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    
    steps:
      # Unity 활성화 요청 파일 생성
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: webbertakken/unity-request-manual-activation-file@v1.1
        with:
          unityVersion: ${{ env.unityVersion }}

      # 요청 파일을 Artifacts로 업로드
      - name: Upload activation request file
        uses: actions/upload-artifact@v3
        with:
          name: unity_activation_request_file
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
